using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
/// <summary>
/// File:           Program.cs
/// Description:    A console application that allows the user to play one or more games of Bulls and Cows
/// Author:         Peter Maxwell
/// Date:           2019/08/20
/// Version:        1.0       
/// </summary>
namespace Activity02
{
    class Program
    {
        static void Main(string[] args)
        {
            //used to access methods in the method class
            BullsAndCows methods = new BullsAndCows();

            string welcomeMessage = "\n\t\t\t\tBulls and Cows\n\nINSTRUCTIONS: Guess a set of 4 random numbers in the correct order.\nYou have 8 attempts to get them right!\n\nPress any key to continue ...";

            //holds the correct numbers generated by the computer
            string[] correctNumbers = new string[4];
            //holds the numbers input as a user guess
            string[] userGuess = new string[4];
            //holds the current turn the user is on
            int userTurnNumber = 1;
            //holds the number of bulls and cows for the current round
            int[] bullsAndCows = new int[2];

            //used to control main game loop
            bool activeGame = true;
            //used to decide if the game should be played again
            bool playAgain = true;
            //used to track how many games are won/lose (0=won games, 1=lost games)
            int[] gamesWonAndLost = new int[2];

            string playerInput = "";

            //writes welcome message in the console window
            Console.WriteLine(welcomeMessage);
            Console.ReadKey();

            //Active game loop starts here
            while (playAgain)
            {
                //clear console window
                Console.Clear();
                //prompt user to input a four digit number guess
                Console.Write("\nA secret 4-digit number has been randomly chosen!");

                //generates four random numbers (minimum int of 0, maximum int of 9)
                correctNumbers = methods.GenerateRandomNumber(0, 9, 4);
                //sets variables to initial values
                userTurnNumber = 1;

                while (activeGame)
                {
                    Console.Write("\n\nYou are on turn {0} of 8\n\nEnter your 4 - digit number ==> ", userTurnNumber);

                    //stores player input
                    playerInput = Console.ReadLine();

                    //VERIFY USER INPUT IS CORRECT HERE
                    if (methods.VerifyPlayerInput(playerInput))
                    {
                        //creates an array from console line, each element holds a single character
                        userGuess = methods.StringToArray(playerInput);

                        bullsAndCows = methods.CountBullsAndCows(userGuess, correctNumbers);

                        //prints the number of bulls and cows found by the player this round
                        Console.WriteLine("\nThere are {0} bulls and {1} cows\n-----", bullsAndCows[0], bullsAndCows[1]);

                        //if player has guessed the correct four digit numbers and order
                        if (bullsAndCows[0] == 4)
                        {
                            Console.WriteLine("\n---------------------------------------------\nCongratulations! You've found all the bulls\n---------------------------------------------");
                            //sets active game to false, exiting the while loop
                            activeGame = false;
                            //+1 to games won
                            gamesWonAndLost[0]++;
                        }
                        else
                        {
                            //if user turn is less than 8
                            if (userTurnNumber < 8)
                            {
                                //increases the user turn number
                                userTurnNumber++;
                            }
                            //if user turn is greater than or equal to 8
                            else if (userTurnNumber >= 8)
                            {
                                //prints game over/lose message
                                Console.WriteLine("\nYou've run out of guesses, wow you really suck!");
                                //sets active game to false, exiting the while loop
                                activeGame = false;
                                //+1 to games lost
                                gamesWonAndLost[1]++;
                            }
                        }
                    }
                    else
                    {
                        Console.WriteLine("Incorrect input entered. Correct input is a 4-digit number e.g. 1234");
                    }
                }

                Console.WriteLine("Games won: {0}\nGames lost: {1}", gamesWonAndLost[0], gamesWonAndLost[1]);
                Console.Write("Would you like to play again? y/n ==> ");
                playerInput = Console.ReadLine();

                //player does not want to play again
                if (playerInput == "n")
                {
                    //exits loop, making the console window close
                    playAgain = false;
                }
                //players wants to play again
                else
                {
                    //sets up program to play a new game of Bulls and Cows
                    activeGame = true;
                }
            }
        }
    }

    class BullsAndCows
    {
        /// <summary>
        /// Returns true if player input is correctly formatted (0000)
        /// </summary>
        public bool VerifyPlayerInput(string input)
        {
            //if all characters input are numbers, and there are four characters in total
            if (input.All(char.IsDigit) && input.Length == 4)
            {
                //correct input was given, return true
                return true;
            }

            //incorrect input was given, return false;
            return false;
        }

        /// <summary>
        /// Turns a string into an array of characters
        /// </summary>
        public string[] StringToArray(string input)
        {
            //creates array that is the same size as there are characters in input string
            string[] outputString = new string[input.Length];

            //splits input string into individual characters and stores them in outputString array
            for (int i = 0; i < input.Length; i++)
            {
                outputString[i] = input.ElementAt(i).ToString();
            }

            return outputString;
        }

        /// <summary>
        /// Returns a random four-digit number as string array
        /// </summary>
        /// <returns></returns>
        public string[] GenerateRandomNumber(int minimumInt, int maximumInt, int numbersToGenerate)
        {
            //used to generate random numbers
            Random randomNumbers = new Random();
            //used to store the randomly generated numbers
            string[] generatedNumbers = new string[numbersToGenerate];

            for (int i = 0; i < numbersToGenerate; i++)
            {
                //generates a random number from minimumInt to maximumInt
                generatedNumbers[i] = randomNumbers.Next(minimumInt, maximumInt - 1).ToString();
            }

            //returns the randomly generated 4-digit number
            return generatedNumbers;
        }

        /// <summary>
        /// Counts how many bulls and cows are in a string
        /// </summary>
        public int[] CountBullsAndCows(string[] userInputString, string[] correctAnswerString)
        {
            //initialize variable
            int[] outputBullsandCowsCount = new int[2];

            //check for bulls and cows
            for (int i = 0; i < correctAnswerString.Length; i++)
            {
                //if a user guess array element matches the same position and value as one of the correct numbers
                if (userInputString[i] == correctAnswerString[i])
                {
                    //+1 to bulls count
                    outputBullsandCowsCount[0]++;
                }
                //if a user guess array element matches the same value as one of the correct numbers
                else if (userInputString.Contains(correctAnswerString[i]))
                {
                    //+1 to cows count
                    outputBullsandCowsCount[1]++;
                }
            }

            //return bulls and cows count
            return outputBullsandCowsCount;
        }
    }
}
